"""
quantbt
=======
Vectorised Binance-Futures backtest SDK.

Quick start
-----------
Single symbol::

    from quantbt import BacktestEngine

    bt = BacktestEngine(
        Datetime        = df["Datetime"],
        Position        = signal,          # pd.Series of weights
        Close           = df["Close"],
        fee             = 0.0004,
        initial_capital = 20_000,
        leverage        = 10,
        hedge_type      = "signal_notional",
        alloc_per_trade = 100_000,
    )
    bt.analyze()                           # text report + chart
    result = bt.result                     # BacktestResult dataclass

Multi-symbol portfolio::

    from quantbt import MultiSymbolPortfolio

    msp = MultiSymbolPortfolio(
        positions  = {"BTC": pos_btc, "ETH": pos_eth},
        closes     = {"BTC": close_btc, "ETH": close_eth},
        datetime_index = common_dt,
        mode       = "market_neutral",
        asset_type = "crypto",
    )
    msp.analyze()

Advanced — standalone metrics + plots::

    from quantbt.metrics import full_report, sharpe, max_drawdown
    from quantbt.viz     import quick_plot, tearsheet

    rpt = full_report(result)
    quick_plot(result, theme="light")
    tearsheet(result)
"""

from importlib import import_module


_LAZY_EXPORTS = {
    **{
        name: (".optimization", name)
        for name in (
            "CONSTRAINTS_USER_ATTR",
            "ArbitrageGenericEvaluator",
            "ArbitrageTrialOutput",
            "CandidateSelector",
            "GenericEndpointEvaluator",
            "GridDCAGenericEvaluator",
            "GridDCATrialOutput",
            "JsonlOptimizationLogger",
            "MissingOptimizationMetricError",
            "MultiSeedOptimization",
            "ObjectiveResult",
            "OptionPackageGenericEvaluator",
            "OptionTrialOutput",
            "OptimizationConfig",
            "OptimizationResult",
            "OptimizationTrialRecord",
            "OptunaOptimizer",
            "PreparedIntrabarEvaluator",
            "PreparedNativeEventStrategyEvaluator",
            "PreparedPortfolioEvaluator",
            "PreparedSignalEvaluator",
            "ReportMetricObjective",
            "RobustSelectionConfig",
            "SamplerConfig",
            "SearchSpaceInfo",
            "SelectedCandidate",
            "SharpeObjective",
            "SingleObjectiveEarlyStopping",
            "TrialEvaluator",
            "build_grid_search_space",
            "build_sampler",
            "constraints_feasible",
            "constraints_from_trial",
            "max_drawdown_constraint",
            "max_margin_utilization_constraint",
            "max_rejection_rate_constraint",
            "max_turnover_constraint",
            "metric_from_result",
            "metrics_from_result",
            "min_trades_constraint",
            "result_full_report",
            "search_space_info",
            "set_trial_constraints",
            "stable_params_key",
            "suggest_parameter",
            "suggest_params",
        )
    },
    **{
        name: (".walkforward", name)
        for name in (
            "DuplicatePruner",
            "EarlyStoppingCallback",
            "WalkForwardBenchmarkSnapshot",
            "WalkForwardCompatibilityEntry",
            "WalkForwardConfig",
            "WalkForwardEngine",
            "WalkForwardFold",
            "PreparedWalkForwardContext",
            "WalkForwardResult",
            "WalkForwardTrialRecord",
            "benchmark_walkforward_kernels",
            "logging_callback",
            "score_strategy_output",
            "select_full_sample_robust_record",
            "select_is_plateau_robust_record",
            "select_is_only_robust_record",
            "select_flat_minima_record",
            "stationary_bootstrap_sharpes",
            "synthetic_walkforward_sharpes",
            "stitch_oos_outputs",
            "strategy_return_series",
            "trade_frequency_penalty",
            "validate_param_ranges",
            "volatility_regime_labels",
            "validate_walkforward_strategy_output",
            "walkforward_support_matrix",
        )
    },
    "quick_plot": (".viz", "quick_plot"),
    "tearsheet": (".viz", "tearsheet"),
    "apply_theme": (".viz", "apply_theme"),
    **{
        name: (".reporting", name)
        for name in (
            "build_arbitrage_domain_audit",
            "build_native_nautilus_parity_report",
            "build_nautilus_certification_profile",
            "build_nautilus_depth_execution_report",
            "build_nautilus_depth_parity_summary",
            "build_nautilus_pct_equity_diagnostic",
            "build_portfolio_domain_audit",
            "build_portfolio_nautilus_position_report",
            "build_portfolio_nautilus_validation_report",
            "compare_native_arbitrage_results",
            "export_nautilus_report_bundle",
            "NautilusToleranceProfile",
            "summarize_native_nautilus_parity_report",
            "write_nautilus_certification_artifacts",
        )
    },
}


def __getattr__(name: str):
    """Resolve optional/heavy public exports on first use."""

    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as exc:  # pragma: no cover - normal Python attribute error
        raise AttributeError(name) from exc
    value = getattr(import_module(module_name, __name__), attribute_name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(_LAZY_EXPORTS))


from .backtester import BacktestEngine
from .portfolio  import MultiSymbolPortfolio
from .endpoint import (
    EndpointConfig,
    NativeEventProfile,
    PreparedIntrabarRunner,
    PreparedNativeEventStrategyRunner,
    QuantBTEndpoint,
    QuantBTPreparedContext,
    format_metrics_report,
)
from .engines import BacktestEngineV2, EventDrivenBacktestEngine, OptionBacktestEngine, PortfolioBacktestEngine
from .backends   import (
    NativeEventBackend,
    NativeEventConfig,
    NativeEventScoreRequirements,
    NativeOptionBackend,
    NativeOptionConfig,
    NativePortfolioBackend,
    NativePortfolioConfig,
    NativeVectorizedBackend,
    NativeVectorizedConfig,
    OptionSettlementEvent,
    RustBatchedAuditResult,
    RustBatchedChunkResult,
    RustBatchedRunner,
    RustBatchedScoreResult,
    RustBatchedSession,
)
from .adapters.nautilus import NautilusBacktestEngine
from .core.types import BacktestResult
from .core.results import (
    BacktestResultV2,
    NativeAccountingArrays,
    NativeEventScalarScoreResult,
    NativeEventScoreResult,
    OptionBacktestResult,
)
from .core.execution_contract import (
    EXECUTION_CONTRACT_REGISTRY,
    AmbiguityPolicy,
    ExecutionContract,
    FillPhase,
    FundingPhase,
    IntrabarSameBarPolicy,
    LiquidationPriority,
    MarketFillPolicy,
    SignalPhase,
    StopGapPolicy,
    TakeProfitGapPolicy,
    TrailingUpdatePhase,
    get_execution_contract,
)
from .core.event_contracts import (
    BarView,
    CommandOutcome,
    EngineDiagnosticsV1,
    EventClockContract,
    FillDecision,
    LifecycleEventKind,
    LifecycleOrderStatus,
    LifecycleTransition,
    WorkingOrderView,
    EVENT_CLOCK_CONTRACTS,
    EVENT_LIFECYCLE_V2_NEXT_BAR_CLOSE,
    EVENT_LIFECYCLE_V3_NEXT_OPEN,
    NATIVE_EVENT_CONTRACT_FINGERPRINT,
    decide_bar_fill,
    get_event_clock_contract,
    lifecycle_transitions,
    validate_lifecycle_transition,
)
from .core.market_tape import MarketValidationCertificate, PreparedMarketTape, prepare_market_tape
from .core.intrabar_reference import (
    IntrabarEventFlag,
    IntrabarFill,
    IntrabarFillReason,
    IntrabarIntentTape,
    IntrabarLevelMode,
    IntrabarReferenceResult,
    IntrabarSizingMode,
    run_intrabar_reference,
)
from .core.intrabar_session import (
    EntryPositionPolicy,
    IntrabarSessionTape,
    ProtectiveExitReentryPolicy,
    SessionCounterBasis,
    SessionExecutionPolicy,
)
from .core.intrabar_kernel import (
    FillReplayTape,
    NativeFillReplayResult,
    NativeIntrabarKernelResult,
    run_fill_replay_kernel,
    run_intrabar_kernel,
    run_intrabar_session_kernel,
)
from .core.certification import (
    AlphaExecutionClassification,
    CertificationLevel,
    alpha_report_markdown,
    build_alpha_certification_report,
    certify_result_metadata,
    classify_alpha_source,
    scan_alpha_directory,
)
from .core.native_event_capabilities import (
    NATIVE_EVENT_CAPABILITY_MATRIX,
    NATIVE_EVENT_CAPABILITY_MATRIX_VERSION,
    capability_matrix_fingerprint,
    native_event_capability_matrix,
    normalize_native_event_capabilities,
    validate_native_event_capability_matrix,
)
from .core.native_event_parity import (
    DEFAULT_NUMERIC_ATOL,
    NativeEventParityCertificate,
    NativeEventParityError,
    assert_native_event_full_parity,
)
from .core.orders import (
    BasketIntent,
    Fill,
    OrderAction,
    OrderActivationPolicy,
    OrderCommand,
    OrderIntent,
    Trade,
    order_intents_to_lifecycle_commands,
)
from .core.reactive import (
    NativeActiveOrderSnapshot,
    NativeCommandBatch,
    NativeEventStrategy,
    NativeEventStrategyError,
    NativeEventStrategyProtocol,
    NativeFillEvent,
    NativeOrderEvent,
    NativeStrategyContext,
)
from .core.basket import FrozenBasketPlan, build_frozen_basket_orders
from .core.execution_depth import (
    NautilusExecutionDepthConfig,
    PackageDepthPreflightResult,
    SUPPORTED_DEPTH_MODELS,
    l2_replay_available,
    simulate_nautilus_order_package_depth,
)
from .core.structured_orders import (
    BracketOrderSpec,
    DcaGridSpec,
    StructuredOrderPlan,
    build_bracket_order_plan,
    build_dca_grid_order_plan,
)
from .core.arbitrage import (
    ArbExecutionPolicy,
    ArbitrageLeg,
    ArbitragePlan,
    ArbitrageSpec,
    ArbitrageType,
    BasisArbitrageSpec,
    CalendarSpreadSpec,
    ContractType,
    CarryModel,
    CarryModelKind,
    CostModel,
    CostModelKind,
    CrossExchangeArbSpec,
    FundingArbitrageSpec,
    HedgePolicy,
    HedgePolicyKind,
    IndexBasketArbSpec,
    LifecycleModel,
    LifecycleModelKind,
    MarginModel,
    MarginModelKind,
    OptionsVolArbSpec,
    PackageExecutionKind,
    PackageRejection,
    SignalModel,
    SignalModelKind,
    SizingPolicy,
    SizingPolicyKind,
    SpotPerpCashCarrySpec,
    SpreadFormula,
    SpreadFormulaKind,
    StatArbPairSpec,
    TriangularArbSpec,
    build_arbitrage_order_plan,
    round_down_to_step,
)
from .core.constraints import QuantityConstraints, build_quantity_constraints, quantize_signed_quantity
from .core.schema import (
    AccountConfig,
    AssetType,
    BasketExecutionPolicy,
    BasketLegSpec,
    BasketSpec,
    ExecutionConfig,
    FeeModel,
    FillPricePolicy,
    InstrumentSpec,
    LiquiditySide,
    MarginMode,
    OmsMode,
    OrderSide,
    OrderType,
    SameBarPolicy,
    SignalSpec,
    TimeInForce,
)
from .core.portfolio import (
    LEGACY_PORTFOLIO_MODES,
    LEGACY_PORTFOLIO_SIZING_MODES,
    NATIVE_PORTFOLIO_ROADMAP_SIZING_MODES,
    NATIVE_PORTFOLIO_SUPPORTED_SIZING_MODES,
    PortfolioDomainSpec,
    PortfolioMode,
    PortfolioRebalancePolicy,
    PortfolioSizingMode,
    normalize_portfolio_mode,
    normalize_portfolio_sizing_mode,
    normalize_rebalance_policy,
    portfolio_capability_matrix,
    validate_portfolio_result_contract,
)
from .options import (
    CANONICAL_OPTION_CHAIN_COLUMNS,
    ExerciseStyle,
    ExternalOptionMarginValidator,
    GammaScalpingConfig,
    HedgeDecision,
    HedgePathResult,
    IVStatus,
    ImpliedVolResult,
    InstrumentRegistrySignature,
    OptionDecisionFillPolicy,
    OptionDepthFidelity,
    OptionExecutionConfig,
    OptionFeeResult,
    OptionFeeSchedule,
    OptionGreeks,
    OptionHedgeConfig,
    OptionHedgePolicyType,
    OptionInstrumentRegistry,
    OptionInstrumentSpec,
    OptionKind,
    OptionLimitFidelity,
    OptionLiquidationAudit,
    OptionMarginConfig,
    OptionMarginModel,
    OptionMarginRequirement,
    OptionPackageExecutionPolicy,
    OptionPackageExecutionResult,
    OptionPackageIntent,
    OptionPackageLeg,
    OptionLedger,
    OptionPosition,
    OptionPreparedRunCache,
    OptionSelection,
    OptionSelectionFilters,
    OptionSettlementRepresentation,
    OptionSettlementResult,
    OptionStrategyRun,
    OptionTapeSignature,
    OptionVenueConvention,
    PremiumConvention,
    PreparedOptionTape,
    SettlementStyle,
    SurfaceDiagnostics,
    TotalVarianceSurface,
    YEAR_NS,
    available_option_rows,
    binance_european_options_convention,
    black76_intrinsic,
    black76_parity_residual,
    black76_parity_value,
    black76_price,
    build_gamma_scalping_strategy_run,
    butterfly,
    calculate_option_fee,
    calculate_option_margin,
    calendar,
    collar,
    compile_option_package_orders,
    condor,
    covered_call,
    deribit_inverse_option_convention,
    deribit_inverse_fee_schedule,
    deribit_linear_usdc_option_convention,
    deribit_linear_usdc_fee_schedule,
    implied_vol_black76,
    implied_vol_inverse_black76_base,
    inverse_black76_greeks_base,
    inverse_black76_greeks_quote,
    inverse_black76_intrinsic_base,
    inverse_black76_parity_residual_base,
    inverse_black76_parity_value_base,
    inverse_black76_price_base,
    linear_black76_greeks,
    compute_net_option_delta,
    execute_option_package,
    hedge_decision,
    liquidate_option_positions,
    long_call,
    long_put,
    option_expiry_payoff_per_unit,
    option_package_cache_key,
    prepare_option_tape,
    risk_reversal,
    run_delta_hedge_path,
    scale_greeks_to_reporting_currency,
    select_atm_option,
    select_target_delta_option,
    select_target_dte_option,
    select_target_moneyness_option,
    settle_option_expiry,
    short_call,
    short_put,
    straddle,
    strangle,
    vertical,
    validate_option_chain_frame,
)

from .metrics import (
    full_report,
    sharpe,
    sortino,
    calmar,
    omega,
    cagr,
    total_return,
    max_drawdown,
    max_drawdown_pct,
    hitrate,
    profit_factor,
    rolling_sharpe,
    rolling_drawdown,
    option_attribution_report,
    option_report_bundle,
    option_run_manifest,
)


__version__ = "1.0.8"
__author__  = "quantbt"

__all__ = [
    # engines
    "BacktestEngine",
    "BacktestEngineV2",
    "EndpointConfig",
    "EventDrivenBacktestEngine",
    "MultiSymbolPortfolio",
    "NautilusBacktestEngine",
    "NativeEventBackend",
    "NativeEventConfig",
    "NativeEventScoreRequirements",
    "NativeAccountingArrays",
    "NativeEventProfile",
    "NativeActiveOrderSnapshot",
    "NativeCommandBatch",
    "NativeEventScoreResult",
    "NativeEventScalarScoreResult",
    "NativeEventParityCertificate",
    "NativeEventParityError",
    "NativeEventStrategyError",
    "NativeEventStrategy",
    "NativeEventStrategyProtocol",
    "NativeFillEvent",
    "NativeOrderEvent",
    "NativeStrategyContext",
    "NativeOptionBackend",
    "NativeOptionConfig",
    "NativePortfolioBackend",
    "NativePortfolioConfig",
    "NativeVectorizedBackend",
    "NativeVectorizedConfig",
    "OptionBacktestEngine",
    "OptionBacktestResult",
    "OptionSettlementEvent",
    "NautilusExecutionDepthConfig",
    "PackageDepthPreflightResult",
    "PortfolioBacktestEngine",
    "PortfolioDomainSpec",
    "PortfolioMode",
    "PortfolioRebalancePolicy",
    "PortfolioSizingMode",
    "QuantBTEndpoint",
    "PreparedNativeEventStrategyRunner",
    "QuantBTPreparedContext",
    "format_metrics_report",
    "CANONICAL_OPTION_CHAIN_COLUMNS",
    "ExerciseStyle",
    "ExternalOptionMarginValidator",
    "GammaScalpingConfig",
    "HedgeDecision",
    "HedgePathResult",
    "IVStatus",
    "ImpliedVolResult",
    "InstrumentRegistrySignature",
    "OptionDecisionFillPolicy",
    "OptionDepthFidelity",
    "OptionExecutionConfig",
    "OptionFeeResult",
    "OptionFeeSchedule",
    "OptionGreeks",
    "OptionHedgeConfig",
    "OptionHedgePolicyType",
    "OptionInstrumentRegistry",
    "OptionInstrumentSpec",
    "OptionKind",
    "OptionLimitFidelity",
    "OptionLiquidationAudit",
    "OptionMarginConfig",
    "OptionMarginModel",
    "OptionMarginRequirement",
    "OptionPackageExecutionPolicy",
    "OptionPackageExecutionResult",
    "OptionPackageIntent",
    "OptionPackageLeg",
    "OptionLedger",
    "OptionPosition",
    "OptionPreparedRunCache",
    "OptionSelection",
    "OptionSelectionFilters",
    "OptionSettlementRepresentation",
    "OptionSettlementResult",
    "OptionStrategyRun",
    "OptionTapeSignature",
    "OptionVenueConvention",
    "PremiumConvention",
    "PreparedOptionTape",
    "SettlementStyle",
    "SurfaceDiagnostics",
    "TotalVarianceSurface",
    "YEAR_NS",
    "available_option_rows",
    "binance_european_options_convention",
    "black76_intrinsic",
    "black76_parity_residual",
    "black76_parity_value",
    "black76_price",
    "build_gamma_scalping_strategy_run",
    "butterfly",
    "calculate_option_fee",
    "calculate_option_margin",
    "calendar",
    "collar",
    "compile_option_package_orders",
    "condor",
    "covered_call",
    "deribit_inverse_option_convention",
    "deribit_inverse_fee_schedule",
    "deribit_linear_usdc_option_convention",
    "deribit_linear_usdc_fee_schedule",
    "implied_vol_black76",
    "implied_vol_inverse_black76_base",
    "inverse_black76_greeks_base",
    "inverse_black76_greeks_quote",
    "inverse_black76_intrinsic_base",
    "inverse_black76_parity_residual_base",
    "inverse_black76_parity_value_base",
    "inverse_black76_price_base",
    "linear_black76_greeks",
    "long_call",
    "long_put",
    "compute_net_option_delta",
    "execute_option_package",
    "hedge_decision",
    "liquidate_option_positions",
    "option_expiry_payoff_per_unit",
    "option_package_cache_key",
    "prepare_option_tape",
    "risk_reversal",
    "run_delta_hedge_path",
    "scale_greeks_to_reporting_currency",
    "select_atm_option",
    "select_target_delta_option",
    "select_target_dte_option",
    "select_target_moneyness_option",
    "settle_option_expiry",
    "short_call",
    "short_put",
    "straddle",
    "strangle",
    "vertical",
    "validate_option_chain_frame",
    "option_attribution_report",
    "option_report_bundle",
    "option_run_manifest",
    "LEGACY_PORTFOLIO_MODES",
    "LEGACY_PORTFOLIO_SIZING_MODES",
    "NATIVE_PORTFOLIO_ROADMAP_SIZING_MODES",
    "NATIVE_PORTFOLIO_SUPPORTED_SIZING_MODES",
    "build_arbitrage_domain_audit",
    "build_native_nautilus_parity_report",
    "build_nautilus_certification_profile",
    "build_nautilus_depth_execution_report",
    "build_nautilus_depth_parity_summary",
    "build_nautilus_pct_equity_diagnostic",
    "build_portfolio_domain_audit",
    "build_portfolio_nautilus_position_report",
    "build_portfolio_nautilus_validation_report",
    "compare_native_arbitrage_results",
    "export_nautilus_report_bundle",
    "NautilusToleranceProfile",
    "summarize_native_nautilus_parity_report",
    "write_nautilus_certification_artifacts",
    "WalkForwardConfig",
    "WalkForwardEngine",
    "WalkForwardFold",
    "PreparedWalkForwardContext",
    "WalkForwardResult",
    "WalkForwardTrialRecord",
    "WalkForwardBenchmarkSnapshot",
    "WalkForwardCompatibilityEntry",
    "EarlyStoppingCallback",
    "DuplicatePruner",
    "CONSTRAINTS_USER_ATTR",
    "JsonlOptimizationLogger",
    "MultiSeedOptimization",
    "ObjectiveResult",
    "OptimizationConfig",
    "OptimizationResult",
    "OptimizationTrialRecord",
    "OptunaOptimizer",
    "RobustSelectionConfig",
    "SamplerConfig",
    "SearchSpaceInfo",
    "SingleObjectiveEarlyStopping",
    "TrialEvaluator",
    "build_grid_search_space",
    "build_sampler",
    "constraints_from_trial",
    "search_space_info",
    "set_trial_constraints",
    "stable_params_key",
    "suggest_parameter",
    "suggest_params",
    "benchmark_walkforward_kernels",
    "logging_callback",
    "score_strategy_output",
    "select_flat_minima_record",
    "select_full_sample_robust_record",
    "select_is_only_robust_record",
    "select_is_plateau_robust_record",
    "stationary_bootstrap_sharpes",
    "synthetic_walkforward_sharpes",
    "stitch_oos_outputs",
    "strategy_return_series",
    "trade_frequency_penalty",
    "validate_param_ranges",
    "volatility_regime_labels",
    "validate_walkforward_strategy_output",
    "walkforward_support_matrix",
    "BacktestResult",
    "BacktestResultV2",
    "BracketOrderSpec",
    "AccountConfig",
    "AlphaExecutionClassification",
    "DEFAULT_NUMERIC_ATOL",
    "NATIVE_EVENT_CAPABILITY_MATRIX",
    "NATIVE_EVENT_CAPABILITY_MATRIX_VERSION",
    "AmbiguityPolicy",
    "ArbExecutionPolicy",
    "ArbitrageLeg",
    "ArbitragePlan",
    "ArbitrageSpec",
    "ArbitrageType",
    "AssetType",
    "BasisArbitrageSpec",
    "BasketExecutionPolicy",
    "BasketIntent",
    "BasketLegSpec",
    "BasketSpec",
    "CalendarSpreadSpec",
    "CertificationLevel",
    "CarryModel",
    "CarryModelKind",
    "ContractType",
    "CostModel",
    "CostModelKind",
    "CrossExchangeArbSpec",
    "DcaGridSpec",
    "EXECUTION_CONTRACT_REGISTRY",
    "ExecutionConfig",
    "ExecutionContract",
    "FeeModel",
    "Fill",
    "FillReplayTape",
    "FillPricePolicy",
    "FillPhase",
    "FundingPhase",
    "FundingArbitrageSpec",
    "FrozenBasketPlan",
    "HedgePolicy",
    "HedgePolicyKind",
    "IndexBasketArbSpec",
    "InstrumentSpec",
    "IntrabarEventFlag",
    "IntrabarFill",
    "IntrabarFillReason",
    "IntrabarIntentTape",
    "IntrabarLevelMode",
    "IntrabarReferenceResult",
    "IntrabarSessionTape",
    "IntrabarSizingMode",
    "IntrabarSameBarPolicy",
    "EntryPositionPolicy",
    "ProtectiveExitReentryPolicy",
    "SessionCounterBasis",
    "SessionExecutionPolicy",
    "LifecycleModel",
    "LifecycleModelKind",
    "LiquiditySide",
    "LiquidationPriority",
    "MarginMode",
    "MarginModel",
    "MarginModelKind",
    "MarketFillPolicy",
    "MarketValidationCertificate",
    "NativeFillReplayResult",
    "NativeIntrabarKernelResult",
    "OmsMode",
    "OrderAction",
    "OrderActivationPolicy",
    "OrderCommand",
    "OrderIntent",
    "OrderSide",
    "OrderType",
    "QuantityConstraints",
    "OptionsVolArbSpec",
    "PackageExecutionKind",
    "PackageRejection",
    "PreparedMarketTape",
    "PreparedIntrabarRunner",
    "SameBarPolicy",
    "SignalModel",
    "SignalModelKind",
    "SignalSpec",
    "SignalPhase",
    "SizingPolicy",
    "SizingPolicyKind",
    "SpotPerpCashCarrySpec",
    "SpreadFormula",
    "SpreadFormulaKind",
    "StatArbPairSpec",
    "StopGapPolicy",
    "StructuredOrderPlan",
    "TakeProfitGapPolicy",
    "TimeInForce",
    "Trade",
    "TrailingUpdatePhase",
    "TriangularArbSpec",
    "alpha_report_markdown",
    "build_arbitrage_order_plan",
    "build_alpha_certification_report",
    "build_bracket_order_plan",
    "build_quantity_constraints",
    "build_dca_grid_order_plan",
    "build_frozen_basket_orders",
    "certify_result_metadata",
    "classify_alpha_source",
    "get_execution_contract",
    "order_intents_to_lifecycle_commands",
    "prepare_market_tape",
    "normalize_portfolio_mode",
    "normalize_portfolio_sizing_mode",
    "normalize_rebalance_policy",
    "portfolio_capability_matrix",
    "quantize_signed_quantity",
    "round_down_to_step",
    "assert_native_event_full_parity",
    "capability_matrix_fingerprint",
    "native_event_capability_matrix",
    "normalize_native_event_capabilities",
    "validate_native_event_capability_matrix",
    "BarView",
    "CommandOutcome",
    "EngineDiagnosticsV1",
    "EventClockContract",
    "FillDecision",
    "LifecycleEventKind",
    "LifecycleOrderStatus",
    "LifecycleTransition",
    "WorkingOrderView",
    "EVENT_CLOCK_CONTRACTS",
    "EVENT_LIFECYCLE_V2_NEXT_BAR_CLOSE",
    "EVENT_LIFECYCLE_V3_NEXT_OPEN",
    "NATIVE_EVENT_CONTRACT_FINGERPRINT",
    "decide_bar_fill",
    "get_event_clock_contract",
    "lifecycle_transitions",
    "validate_lifecycle_transition",
    "run_fill_replay_kernel",
    "run_intrabar_kernel",
    "run_intrabar_session_kernel",
    "run_intrabar_reference",
    "scan_alpha_directory",
    "SUPPORTED_DEPTH_MODELS",
    "l2_replay_available",
    "simulate_nautilus_order_package_depth",
    "validate_portfolio_result_contract",
    # metrics
    "full_report",
    "sharpe",
    "sortino",
    "calmar",
    "omega",
    "cagr",
    "total_return",
    "max_drawdown",
    "max_drawdown_pct",
    "hitrate",
    "profit_factor",
    "rolling_sharpe",
    "rolling_drawdown",
    # viz
    "quick_plot",
    "tearsheet",
    "apply_theme",
]
