"""
quantbt
=======
Vectorised Binance-Futures backtest SDK.

Quick start
-----------
Single symbol::

    from quantbt import BacktestEngine

    bt = BacktestEngine(
        Datetime        = df["Datetime"],
        Position        = signal,          # pd.Series of weights
        Close           = df["Close"],
        fee             = 0.0004,
        initial_capital = 20_000,
        leverage        = 10,
        hedge_type      = "signal_notional",
        alloc_per_trade = 100_000,
    )
    bt.analyze()                           # text report + chart
    result = bt.result                     # BacktestResult dataclass

Multi-symbol portfolio::

    from quantbt import MultiSymbolPortfolio

    msp = MultiSymbolPortfolio(
        positions  = {"BTC": pos_btc, "ETH": pos_eth},
        closes     = {"BTC": close_btc, "ETH": close_eth},
        datetime_index = common_dt,
        mode       = "market_neutral",
        asset_type = "crypto",
    )
    msp.analyze()

Advanced — standalone metrics + plots::

    from quantbt.metrics import full_report, sharpe, max_drawdown
    from quantbt.viz     import quick_plot, tearsheet

    rpt = full_report(result)
    quick_plot(result, theme="light")
    tearsheet(result)
"""

from .backtester import BacktestEngine
from .portfolio  import MultiSymbolPortfolio
from .endpoint import EndpointConfig, QuantBTEndpoint, QuantBTPreparedContext, format_metrics_report
from .walkforward import (
    DuplicatePruner,
    EarlyStoppingCallback,
    WalkForwardBenchmarkSnapshot,
    WalkForwardCompatibilityEntry,
    WalkForwardConfig,
    WalkForwardEngine,
    WalkForwardFold,
    WalkForwardResult,
    WalkForwardTrialRecord,
    benchmark_walkforward_kernels,
    logging_callback,
    score_strategy_output,
    select_full_sample_robust_record,
    select_is_plateau_robust_record,
    select_is_only_robust_record,
    select_flat_minima_record,
    stationary_bootstrap_sharpes,
    synthetic_walkforward_sharpes,
    stitch_oos_outputs,
    strategy_return_series,
    trade_frequency_penalty,
    validate_param_ranges,
    volatility_regime_labels,
    validate_walkforward_strategy_output,
    walkforward_support_matrix,
)
from .engines import BacktestEngineV2, EventDrivenBacktestEngine, OptionBacktestEngine, PortfolioBacktestEngine
from .backends   import (
    NativeEventBackend,
    NativeEventConfig,
    NativeOptionBackend,
    NativeOptionConfig,
    NativePortfolioBackend,
    NativePortfolioConfig,
    NativeVectorizedBackend,
    NativeVectorizedConfig,
    OptionSettlementEvent,
)
from .adapters.nautilus import NautilusBacktestEngine
from .core.types import BacktestResult
from .core.results import BacktestResultV2, OptionBacktestResult
from .core.orders import BasketIntent, Fill, OrderAction, OrderActivationPolicy, OrderCommand, OrderIntent, Trade
from .core.basket import FrozenBasketPlan, build_frozen_basket_orders
from .core.execution_depth import (
    NautilusExecutionDepthConfig,
    PackageDepthPreflightResult,
    SUPPORTED_DEPTH_MODELS,
    l2_replay_available,
    simulate_nautilus_order_package_depth,
)
from .core.structured_orders import (
    BracketOrderSpec,
    DcaGridSpec,
    StructuredOrderPlan,
    build_bracket_order_plan,
    build_dca_grid_order_plan,
)
from .core.arbitrage import (
    ArbExecutionPolicy,
    ArbitrageLeg,
    ArbitragePlan,
    ArbitrageSpec,
    ArbitrageType,
    BasisArbitrageSpec,
    CalendarSpreadSpec,
    ContractType,
    CarryModel,
    CarryModelKind,
    CostModel,
    CostModelKind,
    CrossExchangeArbSpec,
    FundingArbitrageSpec,
    HedgePolicy,
    HedgePolicyKind,
    IndexBasketArbSpec,
    LifecycleModel,
    LifecycleModelKind,
    MarginModel,
    MarginModelKind,
    OptionsVolArbSpec,
    PackageExecutionKind,
    PackageRejection,
    SignalModel,
    SignalModelKind,
    SizingPolicy,
    SizingPolicyKind,
    SpotPerpCashCarrySpec,
    SpreadFormula,
    SpreadFormulaKind,
    StatArbPairSpec,
    TriangularArbSpec,
    build_arbitrage_order_plan,
    round_down_to_step,
)
from .core.constraints import QuantityConstraints, build_quantity_constraints, quantize_signed_quantity
from .core.schema import (
    AccountConfig,
    AssetType,
    BasketExecutionPolicy,
    BasketLegSpec,
    BasketSpec,
    ExecutionConfig,
    FeeModel,
    FillPricePolicy,
    InstrumentSpec,
    LiquiditySide,
    MarginMode,
    OmsMode,
    OrderSide,
    OrderType,
    SameBarPolicy,
    SignalSpec,
    TimeInForce,
)
from .core.portfolio import (
    LEGACY_PORTFOLIO_MODES,
    LEGACY_PORTFOLIO_SIZING_MODES,
    NATIVE_PORTFOLIO_ROADMAP_SIZING_MODES,
    NATIVE_PORTFOLIO_SUPPORTED_SIZING_MODES,
    PortfolioDomainSpec,
    PortfolioMode,
    PortfolioRebalancePolicy,
    PortfolioSizingMode,
    normalize_portfolio_mode,
    normalize_portfolio_sizing_mode,
    normalize_rebalance_policy,
    portfolio_capability_matrix,
    validate_portfolio_result_contract,
)
from .options import (
    CANONICAL_OPTION_CHAIN_COLUMNS,
    ExerciseStyle,
    ExternalOptionMarginValidator,
    GammaScalpingConfig,
    HedgeDecision,
    HedgePathResult,
    IVStatus,
    ImpliedVolResult,
    InstrumentRegistrySignature,
    OptionDecisionFillPolicy,
    OptionDepthFidelity,
    OptionExecutionConfig,
    OptionFeeResult,
    OptionFeeSchedule,
    OptionGreeks,
    OptionHedgeConfig,
    OptionHedgePolicyType,
    OptionInstrumentRegistry,
    OptionInstrumentSpec,
    OptionKind,
    OptionLimitFidelity,
    OptionLiquidationAudit,
    OptionMarginConfig,
    OptionMarginModel,
    OptionMarginRequirement,
    OptionPackageExecutionPolicy,
    OptionPackageExecutionResult,
    OptionPackageIntent,
    OptionPackageLeg,
    OptionLedger,
    OptionPosition,
    OptionPreparedRunCache,
    OptionSelection,
    OptionSelectionFilters,
    OptionSettlementRepresentation,
    OptionSettlementResult,
    OptionStrategyRun,
    OptionTapeSignature,
    OptionVenueConvention,
    PremiumConvention,
    PreparedOptionTape,
    SettlementStyle,
    SurfaceDiagnostics,
    TotalVarianceSurface,
    YEAR_NS,
    available_option_rows,
    binance_european_options_convention,
    black76_intrinsic,
    black76_parity_residual,
    black76_parity_value,
    black76_price,
    build_gamma_scalping_strategy_run,
    butterfly,
    calculate_option_fee,
    calculate_option_margin,
    calendar,
    collar,
    compile_option_package_orders,
    condor,
    covered_call,
    deribit_inverse_option_convention,
    deribit_inverse_fee_schedule,
    deribit_linear_usdc_option_convention,
    deribit_linear_usdc_fee_schedule,
    implied_vol_black76,
    implied_vol_inverse_black76_base,
    inverse_black76_greeks_base,
    inverse_black76_greeks_quote,
    inverse_black76_intrinsic_base,
    inverse_black76_parity_residual_base,
    inverse_black76_parity_value_base,
    inverse_black76_price_base,
    linear_black76_greeks,
    compute_net_option_delta,
    execute_option_package,
    hedge_decision,
    liquidate_option_positions,
    long_call,
    long_put,
    option_expiry_payoff_per_unit,
    option_package_cache_key,
    prepare_option_tape,
    risk_reversal,
    run_delta_hedge_path,
    scale_greeks_to_reporting_currency,
    select_atm_option,
    select_target_delta_option,
    select_target_dte_option,
    select_target_moneyness_option,
    settle_option_expiry,
    short_call,
    short_put,
    straddle,
    strangle,
    vertical,
    validate_option_chain_frame,
)

from .metrics import (
    full_report,
    sharpe,
    sortino,
    calmar,
    omega,
    cagr,
    total_return,
    max_drawdown,
    max_drawdown_pct,
    hitrate,
    profit_factor,
    rolling_sharpe,
    rolling_drawdown,
    option_attribution_report,
    option_report_bundle,
    option_run_manifest,
)

from .viz import quick_plot, tearsheet, apply_theme
from .reporting import (
    build_arbitrage_domain_audit,
    build_native_nautilus_parity_report,
    build_nautilus_certification_profile,
    build_nautilus_depth_execution_report,
    build_nautilus_depth_parity_summary,
    build_nautilus_pct_equity_diagnostic,
    build_portfolio_domain_audit,
    build_portfolio_nautilus_position_report,
    build_portfolio_nautilus_validation_report,
    compare_native_arbitrage_results,
    export_nautilus_report_bundle,
    NautilusToleranceProfile,
    summarize_native_nautilus_parity_report,
    write_nautilus_certification_artifacts,
)

__version__ = "0.1.0"
__author__  = "quantbt"

__all__ = [
    # engines
    "BacktestEngine",
    "BacktestEngineV2",
    "EndpointConfig",
    "EventDrivenBacktestEngine",
    "MultiSymbolPortfolio",
    "NautilusBacktestEngine",
    "NativeEventBackend",
    "NativeEventConfig",
    "NativeOptionBackend",
    "NativeOptionConfig",
    "NativePortfolioBackend",
    "NativePortfolioConfig",
    "NativeVectorizedBackend",
    "NativeVectorizedConfig",
    "OptionBacktestEngine",
    "OptionBacktestResult",
    "OptionSettlementEvent",
    "NautilusExecutionDepthConfig",
    "PackageDepthPreflightResult",
    "PortfolioBacktestEngine",
    "PortfolioDomainSpec",
    "PortfolioMode",
    "PortfolioRebalancePolicy",
    "PortfolioSizingMode",
    "QuantBTEndpoint",
    "QuantBTPreparedContext",
    "format_metrics_report",
    "CANONICAL_OPTION_CHAIN_COLUMNS",
    "ExerciseStyle",
    "ExternalOptionMarginValidator",
    "GammaScalpingConfig",
    "HedgeDecision",
    "HedgePathResult",
    "IVStatus",
    "ImpliedVolResult",
    "InstrumentRegistrySignature",
    "OptionDecisionFillPolicy",
    "OptionDepthFidelity",
    "OptionExecutionConfig",
    "OptionFeeResult",
    "OptionFeeSchedule",
    "OptionGreeks",
    "OptionHedgeConfig",
    "OptionHedgePolicyType",
    "OptionInstrumentRegistry",
    "OptionInstrumentSpec",
    "OptionKind",
    "OptionLimitFidelity",
    "OptionLiquidationAudit",
    "OptionMarginConfig",
    "OptionMarginModel",
    "OptionMarginRequirement",
    "OptionPackageExecutionPolicy",
    "OptionPackageExecutionResult",
    "OptionPackageIntent",
    "OptionPackageLeg",
    "OptionLedger",
    "OptionPosition",
    "OptionPreparedRunCache",
    "OptionSelection",
    "OptionSelectionFilters",
    "OptionSettlementRepresentation",
    "OptionSettlementResult",
    "OptionStrategyRun",
    "OptionTapeSignature",
    "OptionVenueConvention",
    "PremiumConvention",
    "PreparedOptionTape",
    "SettlementStyle",
    "SurfaceDiagnostics",
    "TotalVarianceSurface",
    "YEAR_NS",
    "available_option_rows",
    "binance_european_options_convention",
    "black76_intrinsic",
    "black76_parity_residual",
    "black76_parity_value",
    "black76_price",
    "build_gamma_scalping_strategy_run",
    "butterfly",
    "calculate_option_fee",
    "calculate_option_margin",
    "calendar",
    "collar",
    "compile_option_package_orders",
    "condor",
    "covered_call",
    "deribit_inverse_option_convention",
    "deribit_inverse_fee_schedule",
    "deribit_linear_usdc_option_convention",
    "deribit_linear_usdc_fee_schedule",
    "implied_vol_black76",
    "implied_vol_inverse_black76_base",
    "inverse_black76_greeks_base",
    "inverse_black76_greeks_quote",
    "inverse_black76_intrinsic_base",
    "inverse_black76_parity_residual_base",
    "inverse_black76_parity_value_base",
    "inverse_black76_price_base",
    "linear_black76_greeks",
    "long_call",
    "long_put",
    "compute_net_option_delta",
    "execute_option_package",
    "hedge_decision",
    "liquidate_option_positions",
    "option_expiry_payoff_per_unit",
    "option_package_cache_key",
    "prepare_option_tape",
    "risk_reversal",
    "run_delta_hedge_path",
    "scale_greeks_to_reporting_currency",
    "select_atm_option",
    "select_target_delta_option",
    "select_target_dte_option",
    "select_target_moneyness_option",
    "settle_option_expiry",
    "short_call",
    "short_put",
    "straddle",
    "strangle",
    "vertical",
    "validate_option_chain_frame",
    "option_attribution_report",
    "option_report_bundle",
    "option_run_manifest",
    "LEGACY_PORTFOLIO_MODES",
    "LEGACY_PORTFOLIO_SIZING_MODES",
    "NATIVE_PORTFOLIO_ROADMAP_SIZING_MODES",
    "NATIVE_PORTFOLIO_SUPPORTED_SIZING_MODES",
    "build_arbitrage_domain_audit",
    "build_native_nautilus_parity_report",
    "build_nautilus_certification_profile",
    "build_nautilus_depth_execution_report",
    "build_nautilus_depth_parity_summary",
    "build_nautilus_pct_equity_diagnostic",
    "build_portfolio_domain_audit",
    "build_portfolio_nautilus_position_report",
    "build_portfolio_nautilus_validation_report",
    "compare_native_arbitrage_results",
    "export_nautilus_report_bundle",
    "NautilusToleranceProfile",
    "summarize_native_nautilus_parity_report",
    "write_nautilus_certification_artifacts",
    "WalkForwardConfig",
    "WalkForwardEngine",
    "WalkForwardFold",
    "WalkForwardResult",
    "WalkForwardTrialRecord",
    "WalkForwardBenchmarkSnapshot",
    "WalkForwardCompatibilityEntry",
    "EarlyStoppingCallback",
    "DuplicatePruner",
    "benchmark_walkforward_kernels",
    "logging_callback",
    "score_strategy_output",
    "select_flat_minima_record",
    "select_full_sample_robust_record",
    "select_is_only_robust_record",
    "select_is_plateau_robust_record",
    "stationary_bootstrap_sharpes",
    "synthetic_walkforward_sharpes",
    "stitch_oos_outputs",
    "strategy_return_series",
    "trade_frequency_penalty",
    "validate_param_ranges",
    "volatility_regime_labels",
    "validate_walkforward_strategy_output",
    "walkforward_support_matrix",
    "BacktestResult",
    "BacktestResultV2",
    "BracketOrderSpec",
    "AccountConfig",
    "ArbExecutionPolicy",
    "ArbitrageLeg",
    "ArbitragePlan",
    "ArbitrageSpec",
    "ArbitrageType",
    "AssetType",
    "BasisArbitrageSpec",
    "BasketExecutionPolicy",
    "BasketIntent",
    "BasketLegSpec",
    "BasketSpec",
    "CalendarSpreadSpec",
    "CarryModel",
    "CarryModelKind",
    "ContractType",
    "CostModel",
    "CostModelKind",
    "CrossExchangeArbSpec",
    "DcaGridSpec",
    "ExecutionConfig",
    "FeeModel",
    "Fill",
    "FillPricePolicy",
    "FundingArbitrageSpec",
    "FrozenBasketPlan",
    "HedgePolicy",
    "HedgePolicyKind",
    "IndexBasketArbSpec",
    "InstrumentSpec",
    "LifecycleModel",
    "LifecycleModelKind",
    "LiquiditySide",
    "MarginMode",
    "MarginModel",
    "MarginModelKind",
    "OmsMode",
    "OrderAction",
    "OrderActivationPolicy",
    "OrderCommand",
    "OrderIntent",
    "OrderSide",
    "OrderType",
    "QuantityConstraints",
    "OptionsVolArbSpec",
    "PackageExecutionKind",
    "PackageRejection",
    "SameBarPolicy",
    "SignalModel",
    "SignalModelKind",
    "SignalSpec",
    "SizingPolicy",
    "SizingPolicyKind",
    "SpotPerpCashCarrySpec",
    "SpreadFormula",
    "SpreadFormulaKind",
    "StatArbPairSpec",
    "StructuredOrderPlan",
    "TimeInForce",
    "Trade",
    "TriangularArbSpec",
    "build_arbitrage_order_plan",
    "build_bracket_order_plan",
    "build_quantity_constraints",
    "build_dca_grid_order_plan",
    "build_frozen_basket_orders",
    "normalize_portfolio_mode",
    "normalize_portfolio_sizing_mode",
    "normalize_rebalance_policy",
    "portfolio_capability_matrix",
    "quantize_signed_quantity",
    "round_down_to_step",
    "SUPPORTED_DEPTH_MODELS",
    "l2_replay_available",
    "simulate_nautilus_order_package_depth",
    "validate_portfolio_result_contract",
    # metrics
    "full_report",
    "sharpe",
    "sortino",
    "calmar",
    "omega",
    "cagr",
    "total_return",
    "max_drawdown",
    "max_drawdown_pct",
    "hitrate",
    "profit_factor",
    "rolling_sharpe",
    "rolling_drawdown",
    # viz
    "quick_plot",
    "tearsheet",
    "apply_theme",
]
