#!/usr/bin/env python3
"""Generate the checked public API inventory from ``src/quantbt/__init__.py``."""

from __future__ import annotations

import argparse
import ast
from hashlib import sha256
import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_INIT = ROOT / "src" / "quantbt" / "__init__.py"
JSON_OUTPUT = ROOT / "contracts" / "generated_public_api_inventory.json"
DOC_OUTPUT = ROOT / "docs" / "architecture" / "public_api_inventory.md"


def _sha256(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def _exports() -> tuple[str, ...]:
    tree = ast.parse(PACKAGE_INIT.read_text(encoding="utf-8"), filename=str(PACKAGE_INIT))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            value = ast.literal_eval(node.value)
            if not isinstance(value, (list, tuple)) or not all(isinstance(item, str) for item in value):
                raise ValueError("quantbt.__all__ must be a literal list of strings")
            duplicates = sorted({item for item in value if value.count(item) > 1})
            if duplicates:
                raise ValueError(f"quantbt.__all__ has duplicate exports: {duplicates}")
            return tuple(value)
    raise ValueError("quantbt.__all__ assignment not found")


def _inventory() -> dict[str, Any]:
    exports = _exports()
    categories = {
        "endpoints": [item for item in exports if item.endswith("Endpoint") or item in {"QuantBTEndpoint", "EndpointConfig"}],
        "engines": [item for item in exports if item.endswith("Engine") or item.endswith("Backend")],
        "contracts": [item for item in exports if "Contract" in item or item.endswith("Policy")],
        "results_and_reports": [item for item in exports if "Result" in item or item in {"full_report", "quick_plot", "tearsheet"}],
        "optimization": [item for item in exports if "Optimization" in item or "WalkForward" in item or item.startswith("select_")],
    }
    return {
        "schema": "quantbt-public-api-inventory-v1",
        "source": str(PACKAGE_INIT.relative_to(ROOT)),
        "source_sha256": _sha256(PACKAGE_INIT),
        "exports": list(exports),
        "categories": {name: sorted(set(items)) for name, items in categories.items()},
    }


def _render_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def _render_docs(payload: dict[str, Any]) -> str:
    lines = [
        "# Public API Inventory",
        "",
        "> Generated by `tools/generate_public_api_inventory.py`; do not edit by hand.",
        "",
        f"The checked source of truth is `{payload['source']}` (`sha256: `{payload['source_sha256']}`).",
        f"This release exposes **{len(payload['exports'])}** root-level names. The full machine-readable list is [`generated_public_api_inventory.json`](../../contracts/generated_public_api_inventory.json).",
        "",
        "## Stable Entry Points",
        "",
        "| Surface | Root exports |",
        "|---|---|",
    ]
    for category, exports in payload["categories"].items():
        preview = ", ".join(f"`{item}`" for item in exports[:12])
        if len(exports) > 12:
            preview += f" and {len(exports) - 12} more"
        lines.append(f"| {category.replace('_', ' ')} | {preview or '-'} |")
    lines.extend(
        (
            "",
            "`quantbt.__all__` is the compatibility inventory. Additions/removals require a public API review, documentation update, and generated-inventory refresh.",
            "",
        )
    )
    return "\n".join(lines)


def generated_outputs() -> dict[Path, str]:
    payload = _inventory()
    return {JSON_OUTPUT: _render_json(payload), DOC_OUTPUT: _render_docs(payload)}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        outputs = generated_outputs()
    except (OSError, SyntaxError, ValueError) as exc:
        print(f"public API inventory failed: {exc}", file=sys.stderr)
        return 1
    stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("stale public API inventory artifacts:", file=sys.stderr)
            print("\n".join(str(path.relative_to(ROOT)) for path in stale), file=sys.stderr)
            return 1
        print("public API inventory check: PASS")
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print("generated public API inventory: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
